#!/bin/bash
#
# Copyright (c) 2017 The Bacardi Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

. $BACARDI_PATH/bootstrap/common/path_info.sh

patch -p0 -f < $(bacardi_path)/examples/electron/.node_addon_api_patch/disable-using-internal-n-api.patch > /dev/null 2>&1
electron-rebuild -f && \
    mkdir -p examples/electron/build/Release && \
    cp build/Release/bacardi.node examples/electron/build/Release
