#!/bin/bash
#
# Copyright (c) 2017 The Bacardi Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

. $BACARDI_PATH/bootstrap/common/path_info.sh
. $BACARDI_PATH/bootstrap/common/platform_info.sh

function apply_format() {
  binary_path=$1
  additional_flags=$2
  python $(third_party_path)/clang-format/git-clang-format --force \
      --binary $binary_path \
      --style Chromium \
      --commit HEAD~20 \
      --extension "c,cc,cpp,h" \
      $additional_flags
}

if is_windows_platform; then
  apply_format $(third_party_path)/clang-format/win/clang-format.exe $@
elif is_linux_platform; then
  apply_format $(third_party_path)/clang-format/linux/clang-format $@
elif is_darwin_platform; then
  apply_format $(third_party_path)/clang-format/mac/clang-format $@
fi
